### ISSUE TITLE
StringEncryption crash my app

### ISSUE THREAD

**Issue by lachguer9** [superblaubeere27/obfuscator#11]
hello when i use StringEncryption:  my app crash when installing on phone but without StringEncryption work will

**Comment by superblaubeere27** [comment]
This obfuscator isn't made for Dalvik VM. But can you tell me how did you do that?

**Comment by lachguer9** [comment]
can i use StringEncryption just for String variable in jar file ?

**Comment by superblaubeere27** [comment]
No. I am working on annotations for methods, fields and classes, but this is not possible. If you want to do this, you can just implement the encryption in your source code. If you need some encryption algorithms, here are the string encryption algorithms of the obfuscator: https://github.com/superblaubeere27/obfuscator/tree/master/obfuscator-core/src/main/java/me/superblaubeere27/jobf/processors/encryption/string

**Comment by lachguer9** [comment]
Thank you for your answer but im talk about Obfuscator tools like "Stringer" he can Obfuscate all String in specific Class if you can add this in your tools it will be great option also

**Comment by superblaubeere27** [comment]
@lachguer9 in fact you can use the scripting tab. `isObfuscationEnabledForClass` just return true if `node.name.equals("your/class/Name")` (please replace `.` with `/`. `your.class.Name` -> `your/class/Name`)

**Comment by lachguer9** [comment]
like this : 
function isObfuscatorEnabledForClass(node) {
    return node.name.equals("co/com/folder/neme");
}

**Comment by superblaubeere27** [comment]
Yes.

**Comment by lachguer9** [comment]
thank you i will test and give you feedback . but if you have documentation about how to use script
