### ISSUE TITLE
Trying to obf a mc plugin

### ISSUE THREAD

**Issue by OmerBenGera** [superblaubeere27/obfuscator#12]
I got this error while trying to do so:
https://pastebin.com/iVtxyC3V

I succeed to obf my plugin with 1.65, but virustotal triggered the plugin as a virus...
Any fixes?

**Comment by superblaubeere27** [comment]
Well, can you send me your configuration?

**Comment by checkium** [comment]
@superblaubeere27 I'm having a smiliar error with two plugins, here are the errors:
https://pastebin.com/raw/s1pjqYWZ
https://pastebin.com/raw/if4xfhmp
And here's the config: 
https://pastebin.com/raw/8PWrnwnX

**Comment by superblaubeere27** [comment]
@checkium Thank you for reporting this issue c: Mangle return is the culprit. I will release an update tomorrow (obfuscator v1.8) which will fix this bug.

**Comment by superblaubeere27** [comment]
@checkium I released a new version. Can you please try it again? 
https://github.com/superblaubeere27/obfuscator/releases/tag/v1.8.0

**Comment by checkium** [comment]
@superblaubeere27 It works :D Thank you

**Comment by OmerBenGera** [comment]
That was also my problem (didnt get notified for no reason, sorry)
I will check it out later

**Comment by OmerBenGera** [comment]
@superblaubeere27 The issue was resolved, thank you!
Another question: Is it possible to make the obfuscated to not be shown as a virus on virustotal?

**Comment by superblaubeere27** [comment]
@OmerBenGera Can you please show me the Virustotal result? :o

**Comment by OmerBenGera** [comment]
@superblaubeere27 https://www.virustotal.com/#/file/41e202310eaad0ba76e0e500fae695f4e5b4a86b383a62941e008984eea64f9e/detection

**Comment by superblaubeere27** [comment]
@OmerBenGera Well, 2 not famous FPs are ok.

**Comment by superblaubeere27** [comment]
@OmerBenGera No. But you can report it as FP

**Comment by OmerBenGera** [comment]
Okay, ty
