### ISSUE TITLE
How Do I Prevent A Certain Class From Being Obfuscated?

### ISSUE THREAD

**Issue by HausemasterIssue** [superblaubeere27/obfuscator#122]
# Bug Report
### Expected Behaviour
i want to leave one of the classes of my java program unobfuscated
### Actual Behaviour
Tell us what happened. If there is an Exception please attach it.
### How to reproduce the behaviour
there is no error, it's just it obf's the class and I don't want it to do that
### Possible fix
some piece of code i can put in to prevent a specific class from being obfed?

**Comment by pp0236** [comment]
https://github.com/superblaubeere27/obfuscator#scripting-tab

example
```
function isObfuscatorEnabledForClass(node) {
	return node.name != "you/class/API"; // no .class
}
```

**Comment by HausemasterIssue** [comment]
Thanks!
