### ISSUE TITLE
Errors with v1.8

### ISSUE THREAD

**Issue by OmerBenGera** [superblaubeere27/obfuscator#14]
https://pastebin.com/HBeSPPYL

**Comment by superblaubeere27** [comment]
The link was removed.

**Comment by superblaubeere27** [comment]
Try using the GUI.

**Comment by OmerBenGera** [comment]
It's fixed. But something else:
Is there a way we can open the obfuscator with a config without the need of loading it each time?

**Comment by superblaubeere27** [comment]
You can use the CLI See #16
