### ISSUE TITLE
Ability to run obfucator through CLI with config specified

### ISSUE THREAD

**Issue by yKsenomorf** [superblaubeere27/obfuscator#16]
Example `java -jar obfuscator-1.8.jar --config "C:\config.json"`

**Comment by checkium** [comment]
+1 for this, also allow for more options such as the ones variable in the GUI

**Comment by superblaubeere27** [comment]
Yes. You can load a config which you can make in GUI mode

**Comment by superblaubeere27** [comment]
Done in 9d05aad

Usage: java -jar obfuscator-1.8.jar --config <config.json> --jarIn test.jar --jarOut test-obf.jar

!!! You still need to specify the input file !!!
