### ISSUE TITLE
invokedynamic

### ISSUE THREAD

**Issue by ByteCode-Dan** [superblaubeere27/obfuscator#2]
invokedynamic instructions which return an array needed to be casted with checkcast opcode

```java
Type type = Type.getReturnType(methodInsn.desc);
if (type.getSort() == Type.ARRAY) {
    insns.add(new TypeInsnNode(CHECKCAST, type.getInternalName()));
}
```

**Comment by superblaubeere27** [comment]
Can you tell me how Invokedynamic obfuscation works? Then I would add it.

**Comment by ByteCode-Dan** [comment]
It replaces method invocations (and sometimes field accesses) with an invokedynamic opcode which was introduced in java 7. The invokedynamic bootstrap returns a CallSite containing a MethodHandle to the target we want to invoke/access.

Virtual invocations use an objectref to invoke upon the object they are instantiated upon so you need to account for this by adding an extra object parameter into the invokedynamic bootstrap (another issue with your invokedynamic transformer, you forgot to account for objectref on stack).

**Comment by superblaubeere27** [comment]
@ByteCode-Dan Can you send me a documentation of invokedynamic? I will start with it

**Comment by ByteCode-Dan** [comment]
Hmmm, there isn't much documentation on it.

https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.10.1.9.invokedynamic

**Comment by superblaubeere27** [comment]
I am working on it. If there's no error, I will commit the changes today.

**Comment by superblaubeere27** [comment]
@ByteCode-Dan Got it. Start the obfuscator with --invokeDynamic. https://github.com/superblaubeere27/obfuscator/releases

**Comment by superblaubeere27** [comment]
+ Field access obfuscation
