### ISSUE TITLE
Minecraft Crash after obfuscation

### ISSUE THREAD

**Issue by Sapu98** [superblaubeere27/obfuscator#23]
All I did was giving the impot and output file location to the obfuscator and then I clicked Obfuscate no config/no extra options (it usually worked for the past versions).
This is Minecraft's crash log https://hastebin.com/ebicimahen.cs
This the obfuscator's log: http://prntscr.com/midl2n

the client I obofuscated is a normal mc hacked client+optifine 

build config: https://hastebin.com/pizuwiwoje.json

**Comment by superblaubeere27** [comment]
(As you already figured out) The bug is caused by Mangle switches. I did not figure out what is causing this bug, but I set it's state from OK to GOOD and disabled it by default. (7bbdf37)

**Comment by superblaubeere27** [comment]
I released a new version which was fixed. https://github.com/superblaubeere27/obfuscator/releases/tag/v1.9.1

**Comment by cookiedragon234** [comment]
Closed due to being fixed v1.9.1
