### ISSUE TITLE
Entity Identifier are missing after Obfuscate

### ISSUE THREAD

**Issue by PATTEMMANIKANTA** [superblaubeere27/obfuscator#25]
getting below error while running jar due to entity identifiers/annotation are missing for Spring JPA project

Unsatisfied dependency expressed through field 'customUserDetailsService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'customUserDetailsService': Unsatisfied dependency expressed through field 'userRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Cannot create inner bean '(inner bean)#6c958565' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#6c958565': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Cannot determine embedded database url for database type NONE. If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (the profiles "DEV" are currently active).

**Comment by superblaubeere27** [comment]
Ok. I can you please attach your config and please add a well formatted exception. I can't read this :c

**Comment by PATTEMMANIKANTA** [comment]
[conf.zip](https://github.com/superblaubeere27/obfuscator/files/2854317/conf.zip)

Hi superblaubeere27,
Attached the config,log and images of decompiled code that after obfuscation annotations and identifiers are missing.Due to that not able to run the jar.Let me know if required anything.Thanks in advance.

**Comment by ItzSomebody** [comment]
I would suggest trying to disable HideMembers. I have had issues in the past with annotations and synthetic/bridge access flags.

**Comment by superblaubeere27** [comment]
@PATTEMMANIKANTA, @ItzSomebody is right. This error is caused by [HideMembers](https://github.com/superblaubeere27/obfuscator/blob/master/src/main/java/me/superblaubeere27/jobf/processors/HideMembers.java) since it sets the field's access to synthetic. Here is a little explanation: 

[13.1. The Form of a Binary](https://docs.oracle.com/javase/specs/jls/se11/html/jls-13.html)

> A binary representation for a class or interface must also contain all of the following:
> [...]
> 11. A construct emitted by a Java compiler must be marked as synthetic if it does not correspond to a construct declared explicitly or implicitly in source code, unless the emitted construct is a class initialization method (JVMS §2.9).
> [...]

Please try to disable HideMembers and tell me if it worked.
