### ISSUE TITLE
Packager ignoring main class input

### ISSUE THREAD

**Issue by ImMichey** [superblaubeere27/obfuscator#26]
# Bug Report
### Expected Behaviour
Packager should work fine, however it doesn't because it ignores the attached main file/package
### Actual Behaviour
Ignores the main file/package input in the Packager GUI section
### How to reproduce the behaviour
Enabled Packager and put in a valid file/package name
### Possible fix
I think you only forgot to pick it up from the JTextField

**Comment by superblaubeere27** [comment]
Fixed in 8dcfcb7

**Comment by superblaubeere27** [comment]
Added in release v1.9.2: https://github.com/superblaubeere27/obfuscator/releases/tag/v1.9.2
