### ISSUE TITLE
How to obfuscate a MixinMod with obfuscator

### ISSUE THREAD

**Issue by liaic** [superblaubeere27/obfuscator#28]

**Comment by superblaubeere27** [comment]
You can use the Scripting-Tab. Just exclude the injection classes.
```JavaScript
function isRemappingEnabledForClass(node) {
    return false;
}
function isObfuscatorEnabledForClass(node) {
    return !node.name.startsWith("me/name/client/injection");
}
```

**Comment by liaic** [comment]
thinks

**Comment by liaic** [comment]
thanks

**Comment by cookiedragon234** [comment]
Looks like this issue has been resolved. For anyone seeing this in future releases, make sure you add to excluded classes in "Name Obfuscation" tab `me.name.client.injection.**`
