### ISSUE TITLE
Crasher - empty annotation spam

### ISSUE THREAD

**Issue by yKsenomorf** [superblaubeere27/obfuscator#30]
This will add a bunch of blank ("\n\n\n\n" spam) annotations to every method and class, which will let decompilers to endlessly load the jarfile

**Comment by superblaubeere27** [comment]
I didn't understand exactly what you mean.

**Comment by yKsenomorf** [comment]
Code example: 
![java_xCtxWwPYXs](https://user-images.githubusercontent.com/34306421/54442123-20376300-474f-11e9-9122-fd4ba990ff4d.png)

MD5'ed annotations should be replaced to repeated "\n"
Also this should be added to fields

**Comment by superblaubeere27** [comment]
Oh I'll try this. I'll keep you up to date.

**Comment by yKsenomorf** [comment]
Note: annotations are defined inside of a class by `public interface`

**Comment by yKsenomorf** [comment]
I've finally got to do this, after >3 months... lol
Anyway, here's the code:

CrasherProcessor: https://p.reflex.rip/cego.java
Utils: https://p.reflex.rip/faka.java

Note that it will grow RAM usage, I've mostly fixed that. Implement garbage-collection would solve that

**Comment by superblaubeere27** [comment]
@yKsenomorf Oh thank you. I was working on many things and I hadn't enough time to work on Obfuscator. Thank you for implementing it for me C:

**Comment by superblaubeere27** [comment]
@yKsenomorf The empty string only takes up 48KB. This is not a problem with RAM ^^

**Comment by superblaubeere27** [comment]
Added in 2791b2d
