### ISSUE TITLE
Ability to choose custom dictionary (name) for "iI" methods

### ISSUE THREAD

**Issue by yKsenomorf** [superblaubeere27/obfuscator#31]
Obfuscator will choose one of the lines provided from a config file and will use it for the name of a method (string decryption & etc), like in ProGuard

These:
![javaw_Unx7hhIm1V](https://user-images.githubusercontent.com/34306421/54472597-e6f90480-47db-11e9-82b0-39438ed56299.png)

**Comment by superblaubeere27** [comment]
Ok. Enough time passed. I am currently working on name obfuscation, so I'll implement that now

**Comment by superblaubeere27** [comment]
Added in 0fe5ad5
