### ISSUE TITLE
Bridge access on methods

### ISSUE THREAD

**Issue by FinalException** [superblaubeere27/obfuscator#32]
If you add bridge access to any method other than initialization methods Fernflower will not decompile them

Example:
```java
int access = mv.access;
int bridge = Opcodes.ACC_BRIDGE;

if ((bridge & access) == 0) {
    access += bridge;
}

mv.access = access;
```

**Comment by ItzSomebody** [comment]
Fernflower has an option which lets you decompile pass the bridge modifier.

**Comment by superblaubeere27** [comment]
There is already a transformer which does this: HideMembers (https://github.com/superblaubeere27/obfuscator/blob/master/src/main/java/me/superblaubeere27/jobf/processors/HideMembers.java). But thanks for your request c:
