### ISSUE TITLE
Class not found Error

### ISSUE THREAD

**Issue by Wazed-Matthis** [superblaubeere27/obfuscator#33]
# Bug Report
### Actual Behaviour
If I enable name obfuscation it gives me an error saying that Enum is not in the classpath I tried this with other jars too there it is the same
### How to reproduce the behaviour
Toggle Name Obfuscation and obfuscate

**Comment by superblaubeere27** [comment]
oh yes. This is intended ^^ You have to add all jars the program will use as classpath. This means you have to add rt.jar too. (rt.jar is in `jdk1.8.0_181/jre/lib/rt.jar`)
