### ISSUE TITLE
Help by use new version

### ISSUE THREAD

**Issue by range36rus** [superblaubeere27/obfuscator#34]
# Help by keys new version
Hello! I'm trying to use your new version of obfuscator.
There are a couple of questions.

- The key _--watermark_ - this is what we will replace the code, I understand correctly?

- The  _--config_ key - where can I find an example of a configuration file for obfuscation?

Thank!

**Comment by superblaubeere27** [comment]
`--watermark` doesn't do anything (At the time)
`--config` Here you can specify the config which you can build in the Config-Tab in the GUI Mode

**Comment by range36rus** [comment]
Big thanks! You write very cool obfuscator!
