### ISSUE TITLE
MethodTooLargeException

### ISSUE THREAD

**Issue by fluse1367** [superblaubeere27/obfuscator#36]
Hello,
during the process this error occurres:
`org.objectweb.asm.MethodTooLargeException: Method too large: eu/software4you/minecraft/multiversion/UMaterial.<clinit> ()V
	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2089)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:458)
	at me.superblaubeere27.jobf.JObfImpl.lambda$processJar$6(JObfImpl.java:406)
	at java.lang.Thread.run(Unknown Source)`
The class is not placed in the output jar.
As far as i know this error could be caused by Java itself.
A workaround would be if the obfuscator just ignores the class, but still puts it into the output jar.

**Comment by superblaubeere27** [comment]
Ok? A method too large exception? The method must be very large xD Does it obfuscate the rest of the JAR or does it crash? If it just ignores the class file it is just fine.

**Comment by fluse1367** [comment]
The rest of the JAR gets obfuscated normally. The class file itself is nor included in the obfuscated JAR.

**Comment by superblaubeere27** [comment]
@fluse1367 Did you mean `not`? If it is not included in the output it is a bug.

**Comment by fluse1367** [comment]
The JAR gets obfuscated normally. Except that the obfuscator thorws the error and the class file is neither obfuscated nor included in the JAR.
You can see in the unobfuscated JAR, the UMaterial class is included:
![image](https://user-images.githubusercontent.com/18399629/55689408-577ee580-5984-11e9-9aa5-e5d57e7db13c.png)
And in the obfuscated, it is not included, but the other content gets still obfuscated:
![image](https://user-images.githubusercontent.com/18399629/55689420-81380c80-5984-11e9-82ab-df75fdf4f89d.png)

I hope you'll understand my problem now. xD
(Sorry for the communication problems, I'm not a native speaker ^^)

**Comment by superblaubeere27** [comment]
This is a bug

**Comment by JIhua** [comment]
Hit the same issue, any workaround ?

**Comment by superblaubeere27** [comment]
Hello, this error is caused by the structure of the java bytecode. The code of a method can be max. `Short.MAX_VALUE` (https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.9.1). There is no way for me to fix it, because the code length is unknown until the linking process is done :/ The rest of the JAR is still being obfuscated so this hopefully isn't a huge problem. But you can try reducing the code of the method by extracting parts of it to other methods. Sorry for the inconvenience

**Comment by superblaubeere27** [comment]
I just found a workaround. In Java 10 the maximal code size was updated to `Integer.MAX_VALUE`. This should be enough ^^

**Comment by ItzSomebody** [comment]
> I just found a workaround. In Java 10 the maximal code size was updated to `Integer.MAX_VALUE`. Consider using Java 10 if this bug occurrences.

I'm curious to know if this is incorrectly documented. In the JVM spec, Java 10 and up seem to still have the same constraint on the size.

![Capture](https://user-images.githubusercontent.com/23221108/59547166-17416380-8eef-11e9-82d8-b61ab006cf38.PNG)
