### ISSUE TITLE
Capability to skip over missing libraries, and continue obfuscating where it can.

### ISSUE THREAD

**Issue by EmotionalLove** [superblaubeere27/obfuscator#37]
Basically, if a library or two is missing and the obfuscator comes across a statement it can't load, it should be able to continue obfuscating what it is capable of obfuscating and skip the part where it can't. This would be extremely helpful.

**Comment by superblaubeere27** [comment]
It actually is. The only exception is nameobfuscation. So if NameObfuscation is disabled it should work

**Comment by superblaubeere27** [comment]
I added the wontadd Label, but if it doesn't work even if nameobfuscation is disabled, please tell me and then I'll fix it
