### ISSUE TITLE
Libraries are not displayed within a fixed height container

### ISSUE THREAD

**Issue by cyruscook** [superblaubeere27/obfuscator#42]
# Bug Report
### Expected Behaviour
I would expect that when you add libraries to the obfuscator they would be displayed within a fixed height container that can be scrolled to reveal others.

### Actual Behaviour
Instead they keep filing up and pushing down the bottom of the screen, and worse not just on the input/output tab but also every other tab. This prevents me from saving the config which is of course an absolute pain as it means that I have to add all of the libraries each time. It also actually prevents me from even running the tool.

Some screenshots:
https://i.imgur.com/MPwdRcU.png
https://i.imgur.com/dHXlzuo.png

### Possible fix
Make a fixed height container for the libraries and add a scroll bar.

You could also mitigate the tiring task of adding each library by allowing you to enter into a text box all of the required libraries seperated by a newline. That would be really helpful.

Thank you for this amazing tool by the way, it works really well with everything else!

**Comment by superblaubeere27** [comment]
Fixed in 2791b2d
