### ISSUE TITLE
MySQL connection problem

### ISSUE THREAD

**Issue by SyaFR** [superblaubeere27/obfuscator#43]
# Bug Report
try {
					Class.forName("com.mysql.jdbc.Driver");
					Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
					Statement stmt = con.createStatement();
					String sql ="Select * from tbLogin where Username ='"+textField.getText()+"'and Password = '"+passwordField.getText().toString()+"' ";
					ResultSet rs = stmt.executeQuery(sql);
					
					if(rs.next()) {
						JOptionPane.showMessageDialog(null, "Login successful");
						llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllh.llllllllllllllllll();
						frame.dispose();
					}
					else 
						JOptionPane.showMessageDialog(null, "Login unsuccessful");
				}catch(Exception e) {
					
				}
			
				
			}

does not work when you encrypt the file

**Comment by superblaubeere27** [comment]
@SyaFR Why did you close the issue? did you fix the problem?
