### ISSUE TITLE
Obfuscator is breaking my jar (it wasn't before - I think that's because of the plugin size)

### ISSUE THREAD

**Issue by OmerBenGera** [superblaubeere27/obfuscator#47]
# Bug Report
### Expected Behaviour
The plugin should work and not crash because of an error caused by the obfuscator.
### Actual Behaviour
There's an error that is caused by the obfuscator.
https://pastebin.com/K7M62Rkd
### How to reproduce the behaviour
Not sure how to replicate it, I am pretty sure it has to do with the file size tho (maybe I am wrong). Here is my configuration anyways:
https://pastebin.com/yXXdRRXS

**Comment by OmerBenGera** [comment]
(The original plugin size is 740kb)

**Comment by superblaubeere27** [comment]
Disable FlowObfuscator::MangleSwitches

**Comment by OmerBenGera** [comment]
yeah, seems like it works. Looks like this option is broken.
