### ISSUE TITLE
Eset Internet Security Detects Virus

### ISSUE THREAD

**Issue by MkDomain** [superblaubeere27/obfuscator#49]
# Bug Report
### Expected Behaviour
It should not add virus to my jar.
### Actual Behaviour
It adds Java Kryptik.YO virus.
### How to reproduce the behaviour
Make it this not to happen.
(To get the config open the obfuscator in GUI-Mode, goto `Config`, enable `PrettyPrint` and press `Build`)

**Comment by superblaubeere27** [comment]
Same as #46. Read my answere over there.
