### ISSUE TITLE
String Encryption

### ISSUE THREAD

**Issue by DrakMC** [superblaubeere27/obfuscator#57]
Hello, please add feature to the String Encryption. I need to encrypt all strings except one with with specific value. I don't know how to add it. Thank you.

**Comment by DrakMC** [comment]
I don't understand what do you mean. Will I have to modify the source code? The ideal solution would be if it was already in the obfuscator.

**Comment by cookiedragon234** [comment]
Add the obfuscator jar as a dependency in your project and then use the annotations provided.

**Comment by DrakMC** [comment]
How to use annotations? Can you please provide me some example of code? Thank you

**Comment by superblaubeere27** [comment]
@DrakMC @cookiedragon234  This feature is not implemented yet. I planned it for the next release, but I have no time atm to make it

**Comment by cookiedragon234** [comment]
Oh ok, my bad

**Comment by DrakMC** [comment]
> @DrakMC @cookiedragon234 This feature is not implemented yet. I planned it for the next release, but I have no time atm to make it

Thank you so much. I appreciate your efforts. When would you release next update?

**Comment by superblaubeere27** [comment]
The annotation feature? Yes. You will be able to disable obfuscation for methods, fields and classes. But there will be no feature of just leaving out a specific string value. But it is easy to implement, so you could just modify the source code to do so

**Comment by superblaubeere27** [comment]
I will tell you how. You will have to edit this line https://github.com/superblaubeere27/obfuscator/blob/master/obfuscator-core/src/main/java/me/superblaubeere27/jobf/processors/StringEncryptionTransformer.java#L187

Change `if (insnNode.cst instanceof String && ((String) insnNode.cst).length() < 500)`
to `if (insnNode.cst instanceof String && !insnNode.cst.equals("<the string value you wanna exclude>") && ((String) insnNode.cst).length() < 500)`
