### ISSUE TITLE
Open JDK 11 Bug

### ISSUE THREAD

**Issue by luxora** [superblaubeere27/obfuscator#63]
Hi,
I need help:
I when I compile the program in the last post with eclipse and Open JDK 8 it runs fine.
Unfortunately I was forced to upgradle JDK. This means I compile with my Project with OpenJDK 11 and Eclipse. The JAR without obfuscation runs fine.

About the obfuscation
------
The obfuscator needs the infamous `rt.jar` file.
This doesn't exist from JDK 8 onwards. With what am I suppose to replace it?

**Comment by superblaubeere27** [comment]
I added support for `.jmod` files. Those are used from `JDK >= 9`. The replacement for `lib/rt.jar` would be `jmods/java.base.jmod`

**Comment by luxora** [comment]
I didn't get the file, sorry.
Where do i find the java.base.jmod could you give me a path or a download link please?

**Comment by superblaubeere27** [comment]
You have to add the swing module too.
