### ISSUE TITLE
Bad Concat and Bad POP

### ISSUE THREAD

**Issue by wyw900807** [superblaubeere27/obfuscator#71]
I want to know the purpose of Bad Concat and Bad Pop. Through source code, I can know what these functions are doing, but I do not know the benefits of doing this.

**Comment by cookiedragon234** [comment]
Bad concat will just make the source a bit weirder to read.

Bad pop will just make the source very annoying to read by littering lots of `"".length` calls around the code

**Comment by superblaubeere27** [comment]
@wyw900807 Bad Concat will replace `"A: " + stuff` with `String.valueOf(new StringBuilder().append("A:").append(stuff))`
