### ISSUE TITLE
Obfuscation mapping

### ISSUE THREAD

**Issue by kascodingNL** [superblaubeere27/obfuscator#72]
# Feature Request
- The feature I mean is a txt file as a map to translate the obfuscation back to normal, for example; 

lIlIIlIllll = slap.like.now.Epico.AMethod();

- To make fixing errors easier, because now it is actually impossible to fix things, it would also be nice to fix things like this; https://hastebin.com/kopefahesu.

**Comment by superblaubeere27** [comment]
I have 5 weeks of vacation thanks to corona :3 When I work on the obfuscator this is one of the first things to fix for me ;D

**Comment by kascodingNL** [comment]
Wow, I wished my schools closed(The Fucking Netherlands prime minister says it's unnecessary...).

Although thank you for fixing this!

**Comment by kascodingNL** [comment]
How is progress?

**Comment by cookiedragon234** [comment]
I’ve not been able to do anything on this due to large pressure at school but I’ll try to contribute soon :/

**Comment by kascodingNL** [comment]
No problem, school above everything!

**Comment by kascodingNL** [comment]
Any updates?

**Comment by kascodingNL** [comment]
Can i have an update please?

**Comment by cookiedragon234** [comment]
Ive been working on other projects recently, sorry.

If you want to implement it yourself it should be as simple as dumping the map at https://github.com/superblaubeere27/obfuscator/blob/master/obfuscator-core/src/main/java/me/superblaubeere27/jobf/processors/name/NameObfuscation.java#L89

**Comment by kascodingNL** [comment]
No problem! Since I don't know how pull requests work, is it ok that I don't commit it?

**Comment by cookiedragon234** [comment]
Up to you, I think there is a guide on the ReadMe of how to contribute to the main repo tho
