### ISSUE TITLE
Do not handle non-existent classes 

### ISSUE THREAD

**Issue by vvVenom** [superblaubeere27/obfuscator#76]
How to ignore non-existent classes instead of having to import them into the libraries. Like proguard, it provides a dontwarn, which can guarantee to ignore such class without importing libraries

> -dontwarn org.apache.http**

**Comment by superblaubeere27** [comment]
It is currently not possible since the NameObfuscatior has to know if a method is new or overriden. The alternative to this would be to just don't remap the class and every subsequent class of it

**Comment by superblaubeere27** [comment]
I added an option to do so in 3e9b7def78a9094fbac2567ed2b2f26c5de7a0f0

**Comment by vvVenom** [comment]
> I added an option to do so in [3e9b7de](https://github.com/superblaubeere27/obfuscator/commit/3e9b7def78a9094fbac2567ed2b2f26c5de7a0f0)

Is it possible to solve this problem in the future? I think it ’s very troublesome to add library anyway, it bothers me

Just like the old `Proguard` and the [`R8`](https://r8.googlesource.com/r8/) by Google, they don’t seem to need to import the necessary library, and when the class does not exist, they don’t obfuscate the name, instead of throwing an exception, just issuing a suppressible Warning
