### ISSUE TITLE
Exception in thread "main" com.google.gson.JsonSyntaxException:

### ISSUE THREAD

**Issue by a8underscore** [superblaubeere27/obfuscator#78]
crash 
https://paste.gg/p/anonymous/4a023d558502468db029bd6e86d1c9d8

config
https://paste.gg/p/anonymous/ebd272c4314a43abb0f17a6d7f012327

**Comment by cookiedragon234** [comment]
You need to add a `{` at the top of your config

**Comment by a8underscore** [comment]
That is why I closed it :)
